---
title: "Other content"
---

In addition to my publications, I enjoy talking about my research in a more informal way through various blogs, media, and other outreach activities. If you'd like to discuss any aspect of my work, please don't hesitate to [contact me](quentin.leclerc@pasteur.fr)!

## **Blogs**

- Microbiology Society - [“ 'A Sustainable Future' online focus groups”](https://microbiologysociety.org/blog/a-sustainable-future-online-focus-groups.html)
- Wellcome Open Research Blog – [“Usability of publicly available datasets to help combat antimicrobial resistance”](https://blog.wellcomeopenresearch.org/2020/09/15/usability-of-publicly-available-datasets-to-help-combat-antimicrobial-resistance/)
- Microbiology Society – [“An interdisciplinary approach to reveal the dynamics of generalized transduction of antimicrobial resistance genes”](https://microbiologysociety.org/our-work/75th-anniversary-a-sustainable-future/antimicrobial-resistance-amr/antimicrobial-resistance-amr-case-studies/dynamics-of-generalized-transduction-of-amr-genes.html)
- SGUL Library Blog – [“Challenging but rewarding – Wellcome Trust Data Re-use Prize winner, Quentin Leclerc, on reusing open data”](https://stglibrary.wordpress.com/2019/05/02/challenging-but-rewarding-wellcome-trust-data-re-use-prize-winner-quentin-leclerc-on-reusing-open-data/)
- SGUL News – [“Student wins Wellcome Trust data prize for antimicrobial resistance program”](https://www.sgul.ac.uk/news/student-wins-wellcome-trust-data-prize-for-empirical-therapy-guidelines)

<br>

***

## **Media interviews**
- Radio-Canada - ["Les angles morts du deconfinement"](https://ici.radio-canada.ca/ohdio/premiere/emissions/les-annees-lumiere/segments/reportage/356501/covid-deconfinement-vaccin-variant-pandemie)
- El Pais – [“Cuando la información no se ajusta a la realidad de la pandemia”](https://elpais.com/espana/madrid/2021-03-01/cuando-la-informacion-no-se-ajusta-a-la-realidad.html)
- BBC Science Focus – [“The K factor: Nevermind R, here’s the number we need to understand”](https://www.sciencefocus.com/news/the-k-factor-nevermind-r-heres-the-number-we-need-to-understand/)
- La Presse – [“L’interdiction des rassemblements extérieurs ne fait pas l’unanimité”](https://www.lapresse.ca/societe/2020-10-08/covid-19/l-interdiction-des-rassemblements-exterieurs-ne-fait-pas-l-unanimite.php)
- Huffington Post – [“What are super-spreader events – and how can you avoid them?”](https://www.huffingtonpost.co.uk/entry/whats-a-super-spreader-event-and-how-do-you-avoid-them_uk_5f3e5e67c5b66346158154e6)
- Science News – [“COVID-19 case clusters offer lessons and warnings for reopening”](https://www.sciencenews.org/article/coronavirus-covid-19-case-clusters-lessons-warnings-reopening)

<br>

***

## **Other**
- I'm a Scientist Get me out of here - ["Red Zone" (April 2021)](https://red21.imascientist.org.uk/)
- FAIRly Open After Dark podcast – [“Going Viral!”](https://fairlyopenafterdark.podbean.com/e/going-viral/)



